# Generated by Django 2.2.4 on 2020-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_1', models.TextField(blank=True)),
                ('option_2', models.TextField(blank=True)),
                ('option_3', models.TextField(blank=True)),
                ('option_4', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('standard', models.CharField(max_length=50)),
                ('test_id', models.CharField(max_length=50)),
            ],
        ),
    ]
